### ISSUE TITLE
 install error on Mac OS X

### ISSUE THREAD

**Issue by liyunsheng** [EitriumTech/patchwork#2]
```

===Compiling PATCHWORK for your system===
Compiling bsPatch...
Catastrophic installation error making bspatch
PATCHWORK WAS NOT INSTALLED CORRECTLY!!!

Please report this bug to titon1235@gmail.com with your error and system details
/Users/liyunsheng/WorkSpace/Work/Freedom/open_ak_oa_com/node_modules/eitrium-patchwork/preinstall.js:12
    throw err;
          ^
Error: Command failed: /bin/sh -c make bspatch
bspatch.c:39:21: error: unknown type name 'u_char'; did you mean 'char'?
static off_t offtin(u_char *buf)
                    ^~~~~~
                    char
bspatch.c:65:2: error: use of undeclared identifier 'u_char'
        u_char header[32],buf[8];
        ^
bspatch.c:66:2: error: use of undeclared identifier 'u_char'
        u_char *old, *new;
        ^
bspatch.c:66:10: error: use of undeclared identifier 'old'
        u_char *old, *new;
                ^
bspatch.c:66:16: error: use of undeclared identifier 'new'
        u_char *old, *new;
                      ^
bspatch.c:93:12: error: use of undeclared identifier 'header'
        if (fread(header, 1, 32, f) < 32) {
                  ^
bspatch.c:100:13: error: use of undeclared identifier 'header'
        if (memcmp(header, "BSDIFF40", 8) != 0)
                   ^
bspatch.c:104:19: error: use of undeclared identifier 'header'
        bzctrllen=offtin(header+8);
                         ^
bspatch.c:105:19: error: use of undeclared identifier 'header'
        bzdatalen=offtin(header+16);
                         ^
bspatch.c:106:17: error: use of undeclared identifier 'header'
        newsize=offtin(header+24);
                       ^
bspatch.c:137:5: error: use of undeclared identifier 'old'
                ((old=malloc(oldsize+1))==NULL) ||
                  ^
bspatch.c:139:12: error: use of undeclared identifier 'old'
                (read(fd,old,oldsize)!=oldsize) ||
                         ^
bspatch.c:141:6: error: use of undeclared identifier 'new'
        if((new=malloc(newsize+1))==NULL) err(1,NULL);
            ^
bspatch.c:147:43: error: use of undeclared identifier 'buf'
                        lenread = BZ2_bzRead(&cbz2err, cpfbz2, buf, 8);
                                                               ^
bspatch.c:151:19: error: use of undeclared identifier 'buf'
                        ctrl[i]=offtin(buf);
                                       ^
bspatch.c:159:42: error: use of undeclared identifier 'new'
                lenread = BZ2_bzRead(&dbz2err, dpfbz2, new + newpos, ctrl[0]);
                                                       ^
bspatch.c:167:5: error: use of undeclared identifier 'new'
                                new[newpos+i]+=old[oldpos+i];
                                ^
bspatch.c:167:20: error: use of undeclared identifier 'old'
                                new[newpos+i]+=old[oldpos+i];
                                               ^
bspatch.c:178:42: error: use of undeclared identifier 'new'
                lenread = BZ2_bzRead(&ebz2err, epfbz2, new + newpos, ctrl[1]);
                                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [bspatch.o] Error 1

    at ChildProcess.exithandler (child_process.js:715:12)
    at ChildProcess.emit (events.js:101:17)
    at maybeClose (child_process.js:979:16)
    at Socket.<anonymous> (child_process.js:1147:11)
    at Socket.emit (events.js:98:17)
    at Pipe.close (net.js:456:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v1.0.4
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! eitrium-patchwork@0.0.7 install: `node preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eitrium-patchwork@0.0.7 install script 'node preinstall.js'.
npm ERR! This is most likely a problem with the eitrium-patchwork package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node preinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls eitrium-patchwork
npm ERR! There is likely additional logging output above.

```

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

```
make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by EitriumTech** [comment]
Hi Li

The errors that you are seeing are cascading errors resulting from the <sys/types.h> system library not being imported.In recent versions of the the standard libs, these are automatically imported into the working namespace, but yours however does not seem to possess that functionality.I included explicit calls to the types library now in the bspatch.c and bsdiff.c source files.

Would you mind reinstalling from npm with the new patch version and tell me if any new errors arise ? 
Regards Titon

**Comment by liyunsheng** [comment]
still failed, the error seems different
```
npm i     
-
> eitrium-patchwork@0.0.8 install /Users/liyunsheng/WorkSpace/node_modules/eitrium-patchwork
> node preinstall.js

===Compiling PATCHWORK for your system===
Compiling bsPatch...
Catastrophic installation error making bspatch
PATCHWORK WAS NOT INSTALLED CORRECTLY!!!

Please report this bug to titon1235@gmail.com with your error and system details
/Users/liyunsheng/WorkSpace/node_modules/eitrium-patchwork/preinstall.js:12
    throw err;
          ^
Error: Command failed: /bin/sh -c make bspatch
clang: error: cannot specify -o when generating multiple output files
make: *** [bspatch] Error 1

    at ChildProcess.exithandler (child_process.js:715:12)
    at ChildProcess.emit (events.js:101:17)
    at maybeClose (child_process.js:979:16)
    at Socket.<anonymous> (child_process.js:1147:11)
    at Socket.emit (events.js:98:17)
    at Pipe.close (net.js:456:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v1.0.4
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! eitrium-patchwork@0.0.8 install: `node preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eitrium-patchwork@0.0.8 install script 'node preinstall.js'.
npm ERR! This is most likely a problem with the eitrium-patchwork package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node preinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls eitrium-patchwork
npm ERR! There is likely additional logging output above.
```

**Comment by EitriumTech** [comment]
Hi Li
Looks like a problem with your clang compiler trying to produce an optimized bspatch.exe .It's a bit difficult for me to test for clang compatibility at the command line to dynamically modify compiler arguments, and I hadn't originally intended to support Mac as a build platform when I wrote Patchwork. To avoid breaking compatibility , I'll write a new make file targetted specifically for mac operating systems geared towards the lowest common denominator of compiler args. This means that you might have a slightly larger executable in the end than the other platforms.

**Comment by EitriumTech** [comment]
Pushed a new patch on npm Would you mind terribly trying to install again?

**Comment by liyunsheng** [comment]
thank you for your reply so fast.
I just install the 0.0.9 version and failed again
the log is following
```
node preinstall.js

===Compiling PATCHWORK for your system===
Compiling bsPatch...
Catastrophic installation error making bspatch
PATCHWORK WAS NOT INSTALLED CORRECTLY!!!

Please report this bug to titon1235@gmail.com with your error and system details
/Users/liyunsheng/WorkSpace/node_modules/eitrium-patchwork/preinstall.js:12
    throw err;
          ^
Error: Command failed: /bin/sh -c make bspatch
clang: error: no such file or directory: 'bspatch'
make: *** [bspatch] Error 1

    at ChildProcess.exithandler (child_process.js:715:12)
    at ChildProcess.emit (events.js:101:17)
    at maybeClose (child_process.js:979:16)
    at Socket.<anonymous> (child_process.js:1147:11)
    at Socket.emit (events.js:98:17)
    at Pipe.close (net.js:456:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v1.0.4
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

```

**Comment by EitriumTech** [comment]
Hi Li
I rewrote a lot of Colin's original source to make it more OS agnostic as well as modifying the makefile for compilation. Theoretically the only possible errors that can come through now are related to not having some of the BSD C libraries or having a temperamental compiler.

**Comment by liyunsheng** [comment]
still failed

```
 npm i
|
> eitrium-patchwork@0.0.12 install /Users/liyunsheng/WorkSpace/node_modules/eitrium-patchwork
> node preinstall.js

===Compiling PATCHWORK for your system===
Compiling bsPatch...
Catastrophic installation error making bspatch
PATCHWORK WAS NOT INSTALLED CORRECTLY!!!

Please report this bug to titon1235@gmail.com with your error and system details
/Users/liyunsheng/WorkSpace/node_modules/eitrium-patchwork/preinstall.js:31
        throw error;
              ^
Error: Command failed: /bin/sh -c make bspatch
bspatch.cpp:35:20: error: typedef redefinition with different types ('int' vs '__darwin_ssize_t' (aka 'long'))
typedef signed int ssize_t;
                   ^
/usr/include/sys/_types/_ssize_t.h:30:33: note: previous definition is here
typedef __darwin_ssize_t        ssize_t; 
                                ^
bspatch.cpp:167:7: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]
                    (32 + bzctrllen));
                    ^~~~~~~~~~~~~~~~
bspatch.cpp:174:7: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]
                    (32 + bzctrllen + bzdatalen));
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.
make: *** [bspatch.o] Error 1

    at ChildProcess.exithandler (child_process.js:715:12)
    at ChildProcess.emit (events.js:101:17)
    at maybeClose (child_process.js:979:16)
    at Socket.<anonymous> (child_process.js:1147:11)
    at Socket.emit (events.js:98:17)
    at Pipe.close (net.js:456:12)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v1.0.4
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

```
